keys:
  - &sab age1p9ee76x0dlr7tm6v93r64p9ys5tqt9slhg6vyrn76qydh53gwuhsya0zsq
creation_rules:
  - path_regex: secrets/sab/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *sab
  - path_regex: secrets/nz/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *sab
          # - *user_khanelinix_khaneliman
          # - *user_CORE_nixos
          # - *user_khanelimac_khaneliman
