CF_API_EMAIL: ENC[AES256_GCM,data:LasZ1t8avJobQ60ITEHiNw==,iv:OdPlqmdJ7BlnzcIkvjVR6pS/cYk1Dy9sjFFRHLbWcuE=,tag:IpVMkWTzNnhPgqRfRgWDgQ==,type:str]
CF_API_KEY: ENC[AES256_GCM,data:yZj9NO/lQhoV4rQiOhLcxtlFQ6EQVTxSYqChOmdboxVI0Va99te5AQ==,iv:aarhO1d6FzUBtL99ayfdStlpT3CFoI4lUPSkjdIGERc=,tag:ULmqgNgQlYRNn0VIapK6Dw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdhfmp60w854vyg335p4982fqq9l5khdmaulsze0ywn9kupyypyqwm4ww8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3b2ZiSmk5TWs5ajRYT3I1
            Z3hsTkU0ekNHUS9PRVA0RndLY1I2QmFiUDM4Cm0yODF3YUVLUHR6WG14Rlh4dU9F
            b28xVnQ2RU5pRlFSb3RiRElEUTZIYW8KLS0tIG8vUm1CTVRPU1VnK3VoRTRBYVhF
            MkQyOEVkQ0laODUyVXlQYVpiTCtGMHcKok+HpcMv5GNrOLtkVkvOtlJCW/bbxAUg
            9BNXopI1ygxe2ARD6GyQH1WPKvGghC+rEiJVYNG193ugforrdN+uZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dcacppf640rzcfhmpgcm6eehux7lpdcy8336225gyl3kyw46c3ks3f3wta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cFg3U01BejArUUJOcGFs
            b1pSeFgwNmVocjNjV2w1cTAxa2JWRW12b0VjCkwrcTdPMWF1U1VWRlVLRkd6K3lO
            aU81c2J6WWtURlRLRDlVSnU3WmRCZ00KLS0tIHhSVHdQSG1rYWc5YzB4ZXhLT282
            SVdkN2htWTBaLy9jdGJ6S0RocE9JMFUK8yejh6yKp+OLsNFXWHUJzvHnwaGI1yXA
            Y4F7JY6bhXcu8KJGvjgy08ox+n82V6xY9ov1hwhUlfyIZf4H0/bjuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T14:10:03Z"
    mac: ENC[AES256_GCM,data:MFzJC6yp3SQdEbSWO4vTXU10W/JgDzdMoWYI0oeOZzo2xL2ki84OllwBjYGehMfZ3PHSWtCZC4b1tKj0DBIDHMhTjRakPX1nFl/OA04CUaikVPpWsX0fr3bGKmBL9XuKxWQBVfGNt1YdcjClQQ7jJxx/KPXapMtkE3IbYucpxIY=,iv:CS+RBRQrfI0w4M1bJ0h813UlnQZf2wZbh9E6upJTWFc=,tag:aN6c9T8SQ9BTuxBCxghnMA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
