traefik-cf-env: ENC[AES256_GCM,data:g7Xw9UM1FeOFh+R0jGmPl9Gipix2WNilkCw30iDutxduhYCRmh3cye4D43Zy5x31kvdHej0pwlaSgEVbDOfBMoeENezrcDnLd3xqZHks75QleXv8Ujqoag==,iv:w/byUzrl/9+qcMnUERmO7RYpk991WbhRtcBJkIQIF1o=,tag:CxFiyegx/ZhzU+CU0Bkabg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdhfmp60w854vyg335p4982fqq9l5khdmaulsze0ywn9kupyypyqwm4ww8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3b2ZiSmk5TWs5ajRYT3I1
            Z3hsTkU0ekNHUS9PRVA0RndLY1I2QmFiUDM4Cm0yODF3YUVLUHR6WG14Rlh4dU9F
            b28xVnQ2RU5pRlFSb3RiRElEUTZIYW8KLS0tIG8vUm1CTVRPU1VnK3VoRTRBYVhF
            MkQyOEVkQ0laODUyVXlQYVpiTCtGMHcKok+HpcMv5GNrOLtkVkvOtlJCW/bbxAUg
            9BNXopI1ygxe2ARD6GyQH1WPKvGghC+rEiJVYNG193ugforrdN+uZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dcacppf640rzcfhmpgcm6eehux7lpdcy8336225gyl3kyw46c3ks3f3wta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cFg3U01BejArUUJOcGFs
            b1pSeFgwNmVocjNjV2w1cTAxa2JWRW12b0VjCkwrcTdPMWF1U1VWRlVLRkd6K3lO
            aU81c2J6WWtURlRLRDlVSnU3WmRCZ00KLS0tIHhSVHdQSG1rYWc5YzB4ZXhLT282
            SVdkN2htWTBaLy9jdGJ6S0RocE9JMFUK8yejh6yKp+OLsNFXWHUJzvHnwaGI1yXA
            Y4F7JY6bhXcu8KJGvjgy08ox+n82V6xY9ov1hwhUlfyIZf4H0/bjuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-09T13:41:56Z"
    mac: ENC[AES256_GCM,data:6ytcjeG2iT4+1B047wTuLl9dvbsH8mcB6xiTHE44PlWYDZGkEf4+vMgJNoXJp4XSkeNad+tKqcVLEnNXzX+7EM9D1uFdSlFwF59Z5JIKJcIXW4MqG75DqQXF4hr+BltEW5L4ffDacQPip3FdQL3XSREdPNCTtQhQWfiratKnEg8=,iv:8SeLg69BNaTkKi1tsWGxNPNIZQeSzUiRKaiynqk6sm0=,tag:hImVGNPhuSzHRdsxRm6/nQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
