example_key: ENC[AES256_GCM,data:db4wLhDMLwk7qrMdX24=,iv:tL8H78oNaQibOxiEBZpvVVJs58sgtApWrBdvyAEbMXs=,tag:u9/CJLZH5JvLVbXp1W5l2g==,type:str]
nz_sab_ssh_key: ENC[AES256_GCM,data:avcGPKW3n3vI5KGYJB1jxuxMpA236L4UyXWl9JYlA4Y2cMAvqiyx4aWXKADEJIWwOvKZ5xR/kHB81MX3q2eK/pS39Y7u51QLR6VqBmCSUKfNKeakDwqANQsGza6axyJtSIqQKGVhWXw4uQjlz56KWjMM6BMaGDxfX5nb0AQBB0vVPoDwTQPuFv5IRv+hcls0vkjNrEFjSHLDjtXyHnOYxSFxuz2euLJhwe8BuSZjH8dHWd25TYnLFmC9ADt+QGjFEg2xAYUe47WS0wqVEOw5u19/X2Lep0tzyC/KOPVV4mfpnrL2XfHZMJmkqKVHFemksmGhOA6BE7tqOsazODxXjHenP/WsTBiMCCt33XFRsy8czUZx2awSkupNUQJMcXCxF8Ma93MEmWjtC+PbhwgUH46LCYr4TDjICtaDEmhPBGb+TJXVlKE7rbcjdUSJlp7ssV3n9VHt2470zVdczier1NScQWZ1QMmLOCAlieZOd+CRLYjbbVhWo6SMomavnsfCLowB46ddt16l/QgOHjWc04TpmVh/HSvF1lo=,iv:Ld8A1kf+K6hlOSawnjSw4yrYvKRB7X+nYh40Gmk4u9A=,tag:wBVb0axy58EU+RkdgqNj+Q==,type:str]
atuin_key: ENC[AES256_GCM,data:tG7Nj9virYKiPuCnRotex2o/gW6Z0MhOPaSQ6bpehjOr40S4fmUMEjkhlb7K0D/kTO1Ktm5PgkIMnfcYgoHPVg==,iv:pNvTMM2U421tyjrZqAL7uPtGddeALPWhSYlI+XibtGs=,tag:+jFmITYcfP6SJ8ClFy5xhg==,type:str]
env_credentials: ENC[AES256_GCM,data:iHi+SP6Zcc7O3hv/exLYQZrfciDbb2Pwv3jAr2gGUEeuEy5h3opqK7pSt2rL0UaxOE2Si5nhfwlzfqq0duae6nxZB/gXPat2S9SbXPXCbu+XH0GVEAngBsKt7QjbiNsfT3fBHB7bICgjx2VIhTGzxZrXae7PB8T4+SES4h8zJ2d28lg6e9Ze91hqGPgPzocsLNPs2zGHHE0NDLDNBm8X+PdTAbhglLKFTXg64SDnQuIELsJOxpPtYGpoxk8iSxGziRxCXiWJcHC2IRhKAOHi0jAMVf/El20brJHq1Wop/wpxTWi7HHW9+j+gi1ZJHVUXUf9FxaNCioKnbv7QZwmXVkJ5GjY+EGeSrogUMxUHwz7zOMMRptoKE8edu7FhBkm7tZ0zSy9EoeUoZLWM8KeZCNgMLZv8eVRlnk9WXvE5XteR8oKLrws7VTNukv270BOp3z9fKf9zGhjHx4IUzDFsk94i2J80ImHEdNFlVcYzDU7x7JN/xMG6vFkgegMr5AkMyY5iLOOFOKt5l9ZNPg096hJnllmbhZ5DQPHYkmiWxPHrZ6ZuyozJ0SAeMxbiyr5ZTrrwnhIxDiIEgJ0afkCurMnw+GUBH+pUbvYEFTA0PR8h16/cHyqodkifa8vi3fd4Bj+XVslQC4JWg4lhuRQeKwhSWZyxMs3J4m2n3mBvUgd2Kt5HWpgsLo0N2zimP1QiltacF2E5BIIlK3A4Ai1ImKRacOQ67ziklITnZeKAcFMTEsS/OWIhfoIBIWPaBqHF6/vkMuHgVinU1J7rdig84w==,iv:AhwRAXFzVHAiko398jJnGDCi8vUs4f4f/mWQVFNy6Cg=,tag:YZMONNKxLXl/5qmrDxcjhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p9ee76x0dlr7tm6v93r64p9ys5tqt9slhg6vyrn76qydh53gwuhsya0zsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QzQyRlMvSE9hdkZhNnFI
            UlpFSklGWWJWcytHN2pUbTdpMU1oVVdzcXowCmc2TTRxSnJ0Y2R5NHZ1YUtrZG1H
            alFGYkV5M2N5aEdHcDY1bEh5SnZmMXMKLS0tIEpoTmVqQTU5bUpwV2FtSllpeGFU
            RTlDVjZGaHU2Q1RvOFE5UzlZNnNNUGcK/fdxNIcv5Y26JJxHwujLeCBMCrgPjthP
            k1wCh1YSu3WKwhFG1rKfYWgKtQUXEuuqLLm/shWCBIN5jyQOw/g8eg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18rax0jv4pj2yuegt7e5ea2wzu486mz9nl3vhsa09y45lzw8cj58stfdd6d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RUdzd2FUa2hGaGpaWXlK
            T2VhclJVMGtvaTdwdEhaK0JMd2ptVzdISXhjClE1b1BSWmNkWE9lTEc4cnpPVUJN
            NUh5aHJHZzBPMHU0S1EvUytJaUVuWmcKLS0tIHVVWmdzWkNGUXdWbHcwNFpwWnZs
            MDI4dzh1dlBTclVMbUs1WUNVcHVWTXMKyaw1q7LgPNEBq4wr17xUCqpKdXsAMc1j
            hiP85GHGeChwM127bWuv6ae8eEyLVw6prjrB/3E1xsyOfnRGwASj+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jdhfmp60w854vyg335p4982fqq9l5khdmaulsze0ywn9kupyypyqwm4ww8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHK2hKMFlJRkFrbU54VGpn
            TUFHcVZ6ZEEzNnRvMDVWdnUyOC8yQytPTUcwCkhESktURDBRTXcwU0xwMWo1ZHJF
            YkU4UFYwS2lpMXdEQVprOUl2OUpBNTQKLS0tIDFtRk0xT3RudWtzSW9Gc3MwTWxP
            VUlMZGpNMGZjdzl3Nmd5dnJ4eUhRem8KCIJxtTUFgSaw/gHQuN15ffwCIJl4osCP
            4qv2XZ2qhBBhXJtqmzEecMVKE/qeCU0x2Jl2TwaSZdnjwJ9b40Q7tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-20T09:16:01Z"
    mac: ENC[AES256_GCM,data:n4nfSyeKf/yOY+QawRtP3jNfvn3Q0WBdvdvwgmxiKJYX2kNHcku+W5g6Q7G0SqMfuTyqN57/rL2amedZ097edlPD8sKncFGOK/UKaCFgbvuClodsZRwFOm+nDrHQd8tPmpz69Y3FwMAALvpCohpCpQtBfn8NvF/2XgfePXNwFmk=,iv:nq8l3MtmTGhbAX5tvXQ6bGzVwPRs8Dv8uB6T5+N9Dgc=,tag:HMet1hHyYIjUp5vqcbOMZg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
