example_key: ENC[AES256_GCM,data:db4wLhDMLwk7qrMdX24=,iv:tL8H78oNaQibOxiEBZpvVVJs58sgtApWrBdvyAEbMXs=,tag:u9/CJLZH5JvLVbXp1W5l2g==,type:str]
nz_sab_ssh_key: ENC[AES256_GCM,data:avcGPKW3n3vI5KGYJB1jxuxMpA236L4UyXWl9JYlA4Y2cMAvqiyx4aWXKADEJIWwOvKZ5xR/kHB81MX3q2eK/pS39Y7u51QLR6VqBmCSUKfNKeakDwqANQsGza6axyJtSIqQKGVhWXw4uQjlz56KWjMM6BMaGDxfX5nb0AQBB0vVPoDwTQPuFv5IRv+hcls0vkjNrEFjSHLDjtXyHnOYxSFxuz2euLJhwe8BuSZjH8dHWd25TYnLFmC9ADt+QGjFEg2xAYUe47WS0wqVEOw5u19/X2Lep0tzyC/KOPVV4mfpnrL2XfHZMJmkqKVHFemksmGhOA6BE7tqOsazODxXjHenP/WsTBiMCCt33XFRsy8czUZx2awSkupNUQJMcXCxF8Ma93MEmWjtC+PbhwgUH46LCYr4TDjICtaDEmhPBGb+TJXVlKE7rbcjdUSJlp7ssV3n9VHt2470zVdczier1NScQWZ1QMmLOCAlieZOd+CRLYjbbVhWo6SMomavnsfCLowB46ddt16l/QgOHjWc04TpmVh/HSvF1lo=,iv:Ld8A1kf+K6hlOSawnjSw4yrYvKRB7X+nYh40Gmk4u9A=,tag:wBVb0axy58EU+RkdgqNj+Q==,type:str]
atuin_key: ENC[AES256_GCM,data:tG7Nj9virYKiPuCnRotex2o/gW6Z0MhOPaSQ6bpehjOr40S4fmUMEjkhlb7K0D/kTO1Ktm5PgkIMnfcYgoHPVg==,iv:pNvTMM2U421tyjrZqAL7uPtGddeALPWhSYlI+XibtGs=,tag:+jFmITYcfP6SJ8ClFy5xhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p9ee76x0dlr7tm6v93r64p9ys5tqt9slhg6vyrn76qydh53gwuhsya0zsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOEZocndpd25PYWcrUWxF
            NnpsTWVOK1Vwd1VMKzMxSFdEbU04UW5RaTI0CkJHb3Yzd3czV0JDM0p3ZlZrMHFE
            ODZNZSsyYkpIVjkrQUx1dkNkNklvWTAKLS0tIHRjTkQzSUFDTm5ERXFGalRuSjgw
            Z3NmbGhsTUY4NVZKbHlBLzZkc1IyY28KfELt7l2A/IGDFHwXDSqqLAPzawsodNrq
            NUcPOSUJeIabrhz7+/Ho44rSXeV9YxZkj4zqKNcTrZnuuoPqrInXvA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18rax0jv4pj2yuegt7e5ea2wzu486mz9nl3vhsa09y45lzw8cj58stfdd6d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwT3V2a292UXQ5V0s3NGpk
            L2tFQVhsWkJGVGY3a0MxTkpkY2c1aEcydlhzCjN0dllETmFSdWhtMzMvMVRNUmhZ
            MDdvRlNKdGZndk5UdGhabzQyZHZnVnMKLS0tIFFweWpVYU9zVWFiVWFzbi93MDkz
            VXRBZDl2QjhXNnFkRzVrL0JsajhkWkUKRiEBV+qHZO48XE8Ko7+7jgznaD6q9GTP
            LPNdGnNxAB5BrByfgRIq0deaU+C7M6zbqK1lj2FN/ZuNWhsYqpttKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T07:39:07Z"
    mac: ENC[AES256_GCM,data:Wz6ZaiJ/JZ9lJpfeL+/7fz7g3QMqE0BSN3dg97Ay/4TORcYXfLgd/b7S9DkOcrquROcUrTn+Bqv9k9VnBiDYsui5bqnThvLsnB55qd5SHuZDU3ByUXge1pJFv4as1QS6WQQAEZ2IY7Sp8qasEiPSSmf+DXK6o8EsZrkL0ltEWsY=,iv:fUUgIJ+rN+yEkoSJ6ZD7ONQFnWToCjvMWY9YKIP1M2E=,tag:3joTkRUOeK5s54zxIusw2Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
