example_key: ENC[AES256_GCM,data:9C9ZAbnOKbk0TUwu+Q==,iv:3BSxKb7O/Vtbrm0Es1ddhHVkJDMrdasMOt1k/s95iEc=,tag:0E8E4ecmwDClRIrTe1G5hQ==,type:str]
nz_sab_ssh_key: ENC[AES256_GCM,data:IpR02GJ0vRn6tRbkgr+AE0knCDNSMJDXMtqNn8NAl/wLHppl0ys5zcSh9QTOgg3PjmMA298MR5cIIC7GcwGDMNJ4Z5BsjHwGN2d5ZfuSg7XMKKw/rqgaa7xaVAP7nGov8bQ7mWg9qskqn8zDp1gTwddtToTa7FubZde3PdQh8d2tfght69R6SqZg8FJQtW1y81Y6+SLYtMRBydPwrGL1ElTOFPBOzYURfNBapcx6XzSs1eEEdItWRBHWKDU4xDiT2dRkZgduCMABjvs7FvXuViFqVpWRmF0NnjmwPxV9o46nyrvj3Ch6rj2F9cm+VePRhHmy51UYxw/VGofqJ/j2CYaVKOXznWPKlf5ZFyoYF9LZ+pMlqu9n9MQ5csq2pH8vFbMmlWSdHl1dNjjWV5mS17lj5zShdx2JpudjxHaazCiuCZU2A2qw+nt/D+4a4RSZURcUsjgTWgr+RMbwBOnIaxagWYuuv28XLOUNgUm7O7GADnxFZwxuGiV6uTak/F0BXj6Xn/Z1ST0+jAeSj1ro+IgEnmjR8QRukaM=,iv:Ld8A1kf+K6hlOSawnjSw4yrYvKRB7X+nYh40Gmk4u9A=,tag:unc7gq31gx2HadNRK36Vzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p9ee76x0dlr7tm6v93r64p9ys5tqt9slhg6vyrn76qydh53gwuhsya0zsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveUJlTWk3UlhSNXoyRDVY
            TG81Q1d4MHZEUDNwdnNKM2ptZjk4OUJVNzJvCjVBZWVRQ21yQXJwWjgwdEs2NGZl
            aVcxWnRsaUpWc2twR0g1MHNsc1FqaGcKLS0tIHA0Z2p2UGVxT0V4UVJmL1JaSHJ5
            NFJZYUFVWjhWNmZDWnhZSUVBOFhRVTQKIVocxesO36l7nvq1+PdAKMBNZofHisAU
            QcLYEN8VEenzQ0z++ToqCAU30js7Qxal5+Jkzf7ty2ErRV0jZC7yjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T09:19:36Z"
    mac: ENC[AES256_GCM,data:bscVMQXneHdB827zze644kL/aH1Z2C7M7aNFczOPitNrcrq+aa9+a40RUwtnr79rpBX+o1kcCYAzhTI4Ul0EKS3UaXaUK1fRIEU/0ZrQVE2mBFDuVhfbKKqJtdvoh0KK9ZfUMcK7W4lhqIdaQNhmmb/bTVHlE0SdkfQyY3W8WqY=,iv:ceKovQWV2W62XlokiBmgM6sneE2iNjmWKmN6sJfc1tk=,tag:cfvl6IWHSwF0STJI+H4GBA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
