hello: ENC[AES256_GCM,data:l9Vv9CED0oX5KgupqKJfL6g+qJ7u4lOLwBkAmIE8r/C1F8FQlHf8adROBRt4BA==,iv:Vh6yQ0oBIHoZhzm9R49n3DFl8NSbTpnSY5gb3hIIjI4=,tag:Fsc9HRFSFfZVbf2eM+G0Yw==,type:str]
example_key: ENC[AES256_GCM,data:hL1/mneX0HvwPmt9iA==,iv:0s64w2qqYAHThEf8tkXg4MNb4J+G6tmWJ6jZk3MYhak=,tag:nhiFZgHlavoyTBv5zvr9kw==,type:str]
#ENC[AES256_GCM,data:QyOSMWEe5DSgLlLV0AVGOA==,iv:VHRR+NmC8Z8E+6fp298qRBB9SQQfWnRQ9YoeBnkeEHQ=,tag:QqyvpgO9OUsX8V/AYSCrcQ==,type:comment]
example_array:
    - ENC[AES256_GCM,data:TemOdnjWpyCTLNwvTig=,iv:uNxyrQnl2JyKIUiCL3KOvw/wz7/7VAMZMl5+Qj4wf1o=,tag:DhbG3msW2OQ7Tzih9drIAA==,type:str]
    - ENC[AES256_GCM,data:Ns4h8fKbyqI67IGUnao=,iv:nkbJH0DE+8+r4hfyTdOfGtaKxx0EKfzIRFEkDuMAX1o=,tag:mpj6r21loXstTN3u324VNw==,type:str]
example_number: ENC[AES256_GCM,data:BCURUDVfvjNo8Q==,iv:PmyGDxlkBl4O3unuS/pkxMtN+MHuaW+QWr/PoBmoPaw=,tag:ZydHPidZJEIzYp6H5s/44w==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:yGu9cw==,iv:gwszOZtXznKidOhgAQJObfAYdR35grrp/sONdQBvsw8=,tag:4iNKmgn0Kv2bJUF3XSh1wA==,type:bool]
    - ENC[AES256_GCM,data:yoO41aI=,iv:sZu3cllZDgHnN6wZFb4NdPzNGQjHr0QCR5Ci0FydSKQ=,tag:KbPiK9R+dH6WcoLngPa6cQ==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p9ee76x0dlr7tm6v93r64p9ys5tqt9slhg6vyrn76qydh53gwuhsya0zsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UCtMM3E4T1pFb3JiQlRC
            NjV4TVJXZVRlYlArVWJKUlhhY0o4cUk5cjI0CmhZOGMrTWtDVUhUR3pqTmNYLzVk
            UDRiTlB1dXc5SGIxYStERlpZdGk1akkKLS0tIFdvaEs5MkRKSmVxV1RQcmdGQTdl
            eUxGcmNBOEtSOGNzc1NPaG53eVB5cHcKN+1WmR1at8sRAGm+oKjQrvFln9B4pK2r
            IuhygZXTtV9S/MI5FyCKYG6Jr6d4buki0rCHpdxBdEh8pn5RG9qy2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T09:16:14Z"
    mac: ENC[AES256_GCM,data:Q7IN+zb+QgLJeHIzVJ62RtXXeJjxh9Wq7YtW7S4pZaEnQlKi5L38e/5v/sOPz6ewP1YzUPMleLkL5+esRxmXRJMx0G00TzoJlA83IEOx7qOdq1a5nOBMIM6LJratkBNPBDWFS9qqISlPxuq5gf4xI1oM6F0UbluKSacXWmsH2SA=,iv:Dba1u8LSCSCIl6vG4OVqwEBt+MdoACQNcdLQRepiRUM=,tag:ke8bcNCEVoWGFgk9B4RAzQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
