host_mbp16: ENC[AES256_GCM,data:/+4G5DcpkmFO18d6Ei4FI6rpALbb5L4E9Sq/TlzCc3Hdp1Ww/hmGQ/RKa/fmug==,iv:tNuqBvMaywPpsoS3jMTyBqb4dHuuV3y0c4MYOPU6WN8=,tag:nlsBKcawsXoWVrpzIhDrpA==,type:str]
mbp16_sab_ssh_key: ENC[AES256_GCM,data:Jtlu+w==,iv:kfPdUw5m7JgMd4C9oWEl6/9XasDK/SoavloV0V03SqY=,tag:EEKfXbRAlAN5dt04hIDdLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18rax0jv4pj2yuegt7e5ea2wzu486mz9nl3vhsa09y45lzw8cj58stfdd6d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3d2tUbFJ0YUduNGVCaUkw
            c3doY3ZrUE0vSTlubnBJSmw0aGR1V1BvWDB3CmZ4cWhzQzkxVXV2T2ZNNnVDd25z
            QXc0eTh2T0RDanBScmRCSnFFVXpqL2cKLS0tIG9IbnBmaGVMTzNNaUlxM0k1eTVr
            TDcvUjFpVEpqeXNobXBHc0M0aXhuUmMKRTOVF5aeKN+wFV+mkr/BH8pmXgXimhej
            FZ6Thh4aLBvMj85uC+fC2jEQAd14qle9SfVTUnyxlWCehY0RIgTTXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17tnup59gy7jvj65la8nud0y6ukf57w0mueh3e4hxx5npwsa5x44sv765ru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTHhtWmJVS1AwRkg1bnVw
            allvNEg4RXFQbHEyQms2ZWY1SmNyZGJvZTEwClhTY1JvSHY5MnhwbHRlaCt4Znpk
            WHAyNmJ5ZGc4MjJGUnF6RkZNU2s2a28KLS0tIG1Gd25pWE9rdDFCc0VKZ2p4M3VQ
            eFc1YU5mUW1XcC9GS1BoNWM5TVBWK2MKf2D28JvKMo3Vpe5J7tXfDFPA32mfRuoW
            toMaIXiC6rnXvw4W1+WMwh2xG2iq2qEGf0FIey8WPOg1rwHlNov/rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T14:12:32Z"
    mac: ENC[AES256_GCM,data:z/s6JwUZpA3uhCnFUIN/4cMIM2dcIHDoC2RPucKe9xK6QK0yB0EqXwlhn1Uu5cUrRdmkHMpqImo6CVCO5ebpVtJsa6g4CbmNS/TtW93/PqJ1z6Agl+08w3SH/FiolM72cuRPBBc1VDh3EX/e9ZDBVj82e/vMesfxE8n+k5ZvmPI=,iv:rKsHF9MXKUfc6rqboPzG4/WndYvM6g9kWQJ81uA3FSs=,tag:eiokSvx3/XZ4mPRHZd/2Yg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
