#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5

if [[ "$( file -Lb --mime-type "$file")" =~ ^image ]]; then
    # kitty +icat --silent --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file"
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" < /dev/null > /dev/tty
    exit 1
elif [[ "$( file -Lb --mime-type "$file")" =~ ^video ]]; then
    thumb_dir="$HOME/.cache/ffmpegthumbnailer" 
    if [[ ! -d "$thumb_dir" ]]; then
        mkdir -p $thumb_dir
    fi
    md5sum=$(echo $file | md5)
    thumb_file="$thumb_dir/$md5sum.jpg"
    ffmpeg -ss 00:00:05.000 -i "$file" -vframes 1 "$thumb_file" 
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$thumb_file" < /dev/null > /dev/tty
    exit 1
fi

bat --color=always --style=plain "$file"
