#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5

if [[ "$( file -Lb --mime-type "$file")" =~ ^image ]]; then
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" < /dev/null > /dev/tty
    exit 1
elif [[ "$( file -Lb --mime-type "$file")" =~ ^video ]]; then
    thumb_dir="$HOME/.cache/ffmpegthumbnailer" 
    if [[ ! -d "$thumb_dir" ]]; then
        mkdir -p $thumb_dir
    fi
    
    thumb_file="$thumb_dir/$(realpath $file | md5).jpg"
    # ffmpegthumbnailer -i "$file" -o "$thumb_file" -s0 -t15
    ffmpeg -ss 00:00:15.000 -i "$file" -vframes 1 "$thumb_file" 
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$thumb_file" < /dev/null > /dev/tty
    exit 1
fi

bat --color=always --style=plain "$file"
