nz: ENC[AES256_GCM,data:QqEqbfUGLXGEQ7eTVA==,iv:QHxCTnHx40VP0HhO6kNV1rbtZw+RIGgqG2B3yLjX+yE=,tag:WZnwNXuiNGEUyBqymSmgMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p9ee76x0dlr7tm6v93r64p9ys5tqt9slhg6vyrn76qydh53gwuhsya0zsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITHNGWUMxdDZYS3BtL3Ez
            U2FtSVpDSjVaZWJZaDBYZGxLMkNYRWwvc2prCkpCUThqWVRyMElGbHQwQ1hyZGJ2
            VEttT094OG04Y3ZaU1VLRmR3eEtoWVEKLS0tIGlyRFp3SjRIaHFJOGlzaXAxZ0V2
            TUx5U3l1Z1BwMlk4anpzVzVzdDQrZVkK2gKc7E/YKaI91t/iZSVDBeIFn37XnWId
            hFhDtNoFnSJvt00muITLcS7K5XlMu3ipoi474wooCXRJXa7ZjaktLg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ranl5gsq43t0z22s28zdhvfzrvqqpmwqcjc3h6latfa4rrruxpps34vgqj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyakVGbUllNWZuTDZoTDhp
            cFJ2bzlsRW1KTzVvdVdKY0lHc21lbzc3MTJvCmhVUkNoY1NNaEtwSTN1cG9Ia0dB
            UVltd2w4UHpJVWpzZGkwV2hGRWdicG8KLS0tIDd6OU4rYzFlV3lJR1RiQlZETnd4
            VjZFbU11SEpEdU04STBRNWlYdFQzdXMKiP+drST+u6ibahDzPesdV+mRO4z3SXY8
            ubX7wFMv6+hfxvnfkWA7izk9klIp5EfhvgfDNAGusZDgcb26IAEETg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T06:54:55Z"
    mac: ENC[AES256_GCM,data:dNHMYF3GnsJOq1/IkgYeeawCG5GoudRW68MLkQfk1N27IyGG3XDtPi6QvhRcdgQXCvNjdUAj4o6hkT5AYYtHmjjy3Ogo3TtttIg1BWllk5ZR0bUVT1/57w519i9G3fr9q6XCTT442OQmQsGDPNiJmUaaOLsqqBCTn+CeFENulMY=,iv:Gv03Ybztpf4k8b/evkJDx+SDicS5rw4+O2NPbL4cKlQ=,tag:Y1Y3kojptrorLdUYSs+UoQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
