return {
    "lukas-reineke/indent-blankline.nvim",
    event = "BufRead",
    config = function()
        require("indent_blankline").setup {
            char = "┊",
            buftype_exclude = {
                "NvimTree",
                "terminal",
                "term",
                "gitcommit",
                "fugitive",
                "nofile",
                "Greeter",
            },
            filetype_exclude = {
                "alpha",
                "NvimTree",
                "terminal",
                "term",
                "packer",
                "gitcommit",
                "fugitive",
                "nofile",
                "Greeter",
                "TelescopePrompt",
                "Float",
            },
            context_patterns = {
                "class",
                "function",
                "method",
                "block",
                "list_literal",
                "selector",
                "^if",
                "^table",
                "if_statement",
                "while",
                "for",
                "object",
                "start_tag",
                "open_tag",
                "element",
            },
            use_treesitter = true,
            show_current_context = true,
            show_current_context_start = false,
            show_end_of_line = false,
            space_char_blankline = " ",
        }
    end,
}
