return {
    -- { "sbulav/base16" },
    -- {
    --     "fynnfluegge/monet.nvim",
    --     name = "monet",
    --     opts = {
    --         transparent_background = true,
    --         dark_mode = true,
    --     },
    -- },
    {
        "scottmckendry/cyberdream.nvim",
        lazy = false,
        priority = 1000,
        opts = {
            transparent = true,
            borderless_telescope = false,
            extensions = {
                alpha = false,
                blinkcmp = true,
                cmp = false,
                dashboard = false,
                fzflua = false,
                gitpad = false,
                gitsigns = true,
                grapple = false,
                grugfar = false,
                heirline = false,
                helpview = false,
                hop = false,
                indentblankline = false,
                kubectl = false,
                lazy = false,
                leap = false,
                markdown = false,
                markview = false,
                mini = true,
                noice = false,
                neogit = false,
                notify = false,
                rainbow_delimiters = false,
                snacks = true,
                telescope = false,
                treesitter = true,
                treesittercontext = true,
                trouble = false,
                whichkey = false,
            },
        },
    },
}
