exa_mbp16: ENC[AES256_GCM,data:EhMSuCeS5zIuHS5TueLyBpdjr/y3RT6IFiQHE0g61R4EuxLlJs0kBDUZDphEjA==,iv:rEGEA19BS5uAzIFv68m++OVbZ4QOYSZ3A3+xSbuThJM=,tag:r5F7s0CfeEPSEugudHvH/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p9ee76x0dlr7tm6v93r64p9ys5tqt9slhg6vyrn76qydh53gwuhsya0zsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3U2ttNk5TYXJjS2U4a3JP
            SEFxMUhrUnpBUnRXVXhVSmlBZEh4aXR0eVVRCmVzQnZIUzJsT0dYVGxGOHhnRklC
            UkI0cG1CVWMwMG5nYVVvU3AwSyszdE0KLS0tIHJ0OVVid1JmTEl0dlE5V09Tanl4
            MzMxYmJaZEpWZFY4Qm90YmUwZTVDdG8KQbL/JgUCNVgIDVJqYYKMEbsx2xFVtG5+
            lQcxUZK+8QdED9B3O8Q7QHAIuBzsDjoqIzs8pl3Do/52mCSonwWQPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18rax0jv4pj2yuegt7e5ea2wzu486mz9nl3vhsa09y45lzw8cj58stfdd6d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyS0hGMHJoUXU0dE9US3Fw
            TndKUkhYSzM4TzJCOUZEd1h6MDBMSllUVVFNCkdkVHlMbUJrNzY3T1hWVGlaQVFB
            SGU4dVNsQTdCUm9icEJlQURPelI3UVUKLS0tIHl6U09VRytuZVd0VlNDZzF1Qmcy
            SFA4TTdnbXJlR2RyRlk0SXRTWUwyczgK8XxR/GX2mbLRIOg78I0tYKsJ4K67qT22
            ElIowvltv6m0MBI+UHXnYnUUm5EiUY+NN83ew94bbqf9H/1av3AL5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T14:10:29Z"
    mac: ENC[AES256_GCM,data:FwFEoweZ3RN30nK8X3KiiDY8TbXvSqdmGvaSd+6wPctfD8YY708EhikTTjvdsVgm+2p7g08HSo3D2LL/Sc2pUzeZnM7hJVal+UB32xUnYjHrdgFRcfs7BWWBjA69t8hpSVOBscHdyfq4M6rYEeGM2qnsszaBJfrVhLPKM0l1nOo=,iv:dygr1qXyMOmG9T/w5pyhLqnqVz0I3d4lx1AjpCdUsPc=,tag:x6J9bhVOk8aBdUzDk/m/YA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
